# Generated by Django 5.2.5 on 2025-08-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان العرض')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, verbose_name='نسبة الخصم')),
                ('active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'عرض',
                'verbose_name_plural': 'العروض',
                'ordering': ['-created_at'],
            },
        ),
    ]
