# Generated by Django 5.2.4 on 2025-08-14 16:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
        ('products', '0002_product_discount_percent_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='products.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='active',
            field=models.BooleanField(default=True, verbose_name='مفعّل'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='الخصم %'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='العنوان'),
        ),
    ]
