# Generated by Django 5.2.4 on 2025-08-14 18:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_product_alter_offer_active_and_more'),
        ('products', '0002_product_discount_percent_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم (%)'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='products.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان العرض'),
        ),
    ]
