# Generated by Django 5.2.5 on 2025-08-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120, verbose_name='اسم العميل')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإجمالي')),
                ('status', models.CharField(choices=[('pending', 'قيد المعالجة'), ('paid', 'مدفوعة'), ('shipped', 'تم الشحن'), ('completed', 'مكتملة'), ('canceled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
            },
        ),
    ]
